### ISSUE TITLE
local variable 'departures' referenced before assignment

### ISSUE THREAD

**Issue by isabellaalstrom** [DSorlov/hasl-platform#18]
This line:
https://github.com/DSorlov/ha-sensor-sl/blob/36d42f0e2e4559c1ea91745b5bec06e6bbf1e82a/custom_components/hasl/sensor.py#L470

needs to be moved up to before the if, on line 453, otherwise the log errors on line 505 when the sensor is not supposed to be updated, since the variable isn't assigned yet.

`2019-04-30 15:11:37 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.repvagen_2 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/hasl/sensor.py", line 505, in _update
    self._departure_table = sorted(departures, key=lambda k: k['time'])
UnboundLocalError: local variable 'departures' referenced before assignment`

**Comment by DSorlov** [comment]
Actually was everything from line 505 that had for some reason lost indentation so just moved it all in and now seems to be validating this scenario.
