### ISSUE TITLE
My setup (3 sensors with the same departing station) doesn't work - again

### ISSUE THREAD

**Issue by erikatl** [DSorlov/hasl-platform#32]
I am on HA version 0.93.2. And on your hasl branch. Very seldom I have updated information from SL, usually at least half an hour old. These are the error messages I keep getting:
`Update for sensor.helenelund_bussar fails
Traceback (most recent call last):
  File "/config/custom_components/hasl/sensor.py", line 747, in _update_si2
    deviationdata = self._si2api.request()
  File "/config/deps/lib/python3.7/site-packages/hasl/hasl.py", line 124, in request
    self._siteid, self._lines))
  File "/config/deps/lib/python3.7/site-packages/hasl/hasl.py", line 98, in _get
    jsonResponse['Message'])
hasl.exceptions.HASL_API_Error: HASL_API_Error 1007: Unknown API-response code encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 224, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/hasl/sensor.py", line 652, in _update
    self._update_si2()
  File "/config/custom_components/hasl/sensor.py", line 756, in _update_si2
    except HASL_Error as e:
NameError: name 'HASL_Error' is not defined`

**Comment by DSorlov** [comment]
For trouble shooting reasons could you remove the si2key from config and try to see if that changes anything?

**Comment by erikatl** [comment]
I removed si2key from the config, and it changes everything. As in now I get no information at all. And I get a new error message:
"Error while setting up platform hasl
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 126, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hasl/sensor.py", line 125, in setup_platform
    config.get(CONF_USE_MINIMIZATION)
  File "/config/custom_components/hasl/sensor.py", line 460, in __init__
    self._si2datakey = 'si2_' + si2key + '_' + siteid
TypeError: can only concatenate str (not "NoneType") to str"
I am now off for a family "myskväll", but I will look into this again tomorrow morning.

**Comment by erikatl** [comment]
Additional error messages which I haven't seen before, I have no idea if they have with hasl to do:
"Error handling request
21:01 components/recorder/__init__.py (ERROR)
Error executing query: (sqlite3.OperationalError) database is locked (Background on this error at: http://sqlalche.me/e/e3q8)
21:01 components/recorder/util.py (ERROR) - message first occured at 21:01 and shows up 4 times"

**Comment by DSorlov** [comment]
@erikatl I have done some updating to the error handling, could you please try your first scenario again with the code found in the dev-tree?

**Comment by erikatl** [comment]
I updated to the dev-tree version and it works fine. The SL page gets updated fine. And the error messages I got before do not show. 

However, it seems like I have wasted my monthly SI2 API request quota: "A communication error occured while updating SI2 sensor: Too many requests per month"

So I won't be getting any "SL Störningsinformation" for a while I guess. And the RI4 quota is probably also on the brink. Will the used quota be reset on the 1st of June, or do they use any other method, such as a month from the date when I first made a request?

**Comment by DSorlov** [comment]
I actually have no idea except perhaps opening another account.. =)

**Comment by erikatl** [comment]
Sorry if this is inappropiate but I just want to comment on the question I asked regarding when the API quotas are reset. Now it is one hour into June and I believe I am getting "SL Störningsinformation" again:
![Screenshot_20190601_010948](https://user-images.githubusercontent.com/46231369/58739712-10552400-840c-11e9-8204-26947ea9c430.png)
New month, quotas seem to be reset.
